// AUTO-GENERATED by woossh plugin manager.
// Run 'woossh plugin install <url>' to add external plugins.
// INSTALLED: github.com/silveX89/woossh-plugins/tmux | https://github.com/silveX89/woossh-plugins/tmux | official

package main

import (
	_ "github.com/silveX89/woossh-plugins/tmux"
)

func init() {
	// External plugins register themselves via their init() functions.
	// Builtin plugins are imported in main.go via blank imports.
}
